
macro(SLICE2CPP FILEPATH OUTPUT)
get_filename_component(OUTPUT_BASE_NAME ${FILEPATH} NAME_WE)
set(OUTPUT_HEADER_NAME ${OUTPUT_BASE_NAME}.h)
set(OUTPUT_SOURCE_NAME ${OUTPUT_BASE_NAME}.cc)
message(STATUS "HEADER: ${OUTPUT}/${OUTPUT_HEADER_NAME}")
message(STATUS "SOURCE: ${OUTPUT}/${OUTPUT_SOURCE_NAME}")
add_custom_command(OUTPUT ${OUTPUT}/${OUTPUT_HEADER_NAME} ${OUTPUT}/${OUTPUT_SOURCE_NAME}
    COMMAND slice2cpp --source-ext cc --output-dir ${OUTPUT} ${CMAKE_CURRENT_SOURCE_DIR}/${FILEPATH}
    COMMENT "-- Generating ${OUTPUT_HEADER_NAME} ${OUTPUT_SOURCE_NAME}")
endmacro(SLICE2CPP)
macro(SLICE2PY FILEPATH OUTPUT)
get_filename_component(OUTPUT_BASE_NAME ${FILEPATH} NAME_WE)
set(OUTPUT_NAME ${OUTPUT_BASE_NAME}.py)
message(STATUS "PYTHON: ${OUTPUT}/${OUTPUT_NAME}")
add_custom_target(${OUTPUT_NAME} ALL
    slice2py --output-dir ${OUTPUT} ${CMAKE_CURRENT_SOURCE_DIR}/${FILEPATH}
    COMMENT "-- Generating ${OUTPUT_NAME}")
endmacro(SLICE2PY)